use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::time::Duration;

use anyhow::{anyhow, bail, Result};
use itertools::Itertools;
use serde_json::Value;

/// User-facing options for `lifter add github`.
///
/// The command intentionally keeps archive contents out of scope: callers may
/// provide the archive member to extract with `extract`, but lifter does not
/// download or inspect the archive while creating the config entry.
pub struct AddGithubOptions {
    pub repo: String,
    pub section_name: Option<String>,
    pub asset_filter: Option<String>,
    pub extract: Option<String>,
    pub dry_run: bool,
}

/// Summary of the config entry generated by `lifter add github`.
pub struct AddedGithubDefinition {
    pub config_path: PathBuf,
    pub section_name: String,
    pub asset_name: String,
    pub version: String,
    pub entry: String,
    pub wrote_template: bool,
    pub wrote_file: bool,
}

struct GithubRelease {
    tag_name: String,
    assets: Vec<String>,
}

const GITHUB_API_TEMPLATE: &str = "[template:github_api_latest]\nmethod = api_json\npage_url = https://api.github.com/repos/{project}/releases/latest\nversion_tag = $.tag_name\nanchor_tag = $.assets.*.browser_download_url\n";

/// Fetch the latest GitHub release, infer the best asset for this host, and
/// append a `github_api_latest` section to `config_path`.
pub fn add_github_definition(
    config_path: &Path,
    options: &AddGithubOptions,
) -> Result<AddedGithubDefinition> {
    validate_repo(&options.repo)?;
    let existing_config = fs::read_to_string(config_path).unwrap_or_default();
    let section_name = section_name_for_repo(&options.repo, options.section_name.as_deref());
    if !options.dry_run && has_section(&existing_config, &section_name) {
        bail!("config already contains section [{section_name}]; choose another name with --name");
    }

    let release = fetch_latest_release(&options.repo)?;
    let definition = definition_from_release(&options.repo, &release, options)?;
    let needs_template = !has_section(&existing_config, "template:github_api_latest");
    if !options.dry_run {
        append_definition(
            config_path,
            &existing_config,
            needs_template,
            &definition.entry,
        )?;
    }

    Ok(AddedGithubDefinition {
        config_path: config_path.to_path_buf(),
        wrote_template: needs_template,
        wrote_file: !options.dry_run,
        ..definition
    })
}

fn fetch_latest_release(repo: &str) -> Result<GithubRelease> {
    let url = format!("https://api.github.com/repos/{repo}/releases/latest");
    let mut attempts_remaining = 3;
    let response = loop {
        if attempts_remaining == 0 {
            bail!("failed to fetch latest release for {repo}");
        }
        attempts_remaining -= 1;

        let agent = crate::http_agent();
        let request = agent
            .get(&url)
            .header("Accept", "application/vnd.github+json")
            .header("X-GitHub-Api-Version", "2022-11-28")
            .header("User-Agent", "lifter");
        let request = if let Ok(token) = std::env::var("GITHUB_TOKEN") {
            request.header("Authorization", &format!("Bearer {token}"))
        } else {
            request
        };

        let response = request
            .call()
            .map_err(|e| anyhow!("error fetching {url}: {e}"))?;
        match response.status().as_u16() {
            200..=299 => break response,
            403 | 408 | 425 | 429 | 500 | 502 | 503 | 504 if attempts_remaining > 0 => {
                let delay = Duration::from_secs((3 - attempts_remaining) * 2);
                std::thread::sleep(delay);
            }
            status => {
                let body = response.into_body().read_to_string()?;
                bail!("GitHub returned status {status} for {url}: {body}");
            }
        }
    };

    let body = response.into_body().read_to_string()?;
    release_from_json(&body)
}

fn release_from_json(payload: &str) -> Result<GithubRelease> {
    let data: Value = serde_json::from_str(payload)?;
    let tag_name = data
        .get("tag_name")
        .and_then(Value::as_str)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| anyhow!("GitHub release response did not include tag_name"))?
        .to_string();
    let assets = data
        .get("assets")
        .and_then(Value::as_array)
        .ok_or_else(|| anyhow!("GitHub release response did not include an assets array"))?
        .iter()
        .filter_map(|asset| asset.get("name").and_then(Value::as_str))
        .map(str::to_string)
        .collect::<Vec<_>>();

    if assets.is_empty() {
        bail!("latest release has no downloadable assets");
    }

    Ok(GithubRelease { tag_name, assets })
}

fn definition_from_release(
    repo: &str,
    release: &GithubRelease,
    options: &AddGithubOptions,
) -> Result<AddedGithubDefinition> {
    let asset_name = select_asset(&release.assets, options.asset_filter.as_deref())?;
    let section_name = section_name_for_repo(repo, options.section_name.as_deref());
    let anchor_text = anchor_text_for_asset(&asset_name, &release.tag_name);
    let entry = render_definition(
        &section_name,
        repo,
        &anchor_text,
        options.extract.as_deref(),
        &release.tag_name,
    );

    Ok(AddedGithubDefinition {
        config_path: PathBuf::new(),
        section_name,
        asset_name,
        version: release.tag_name.clone(),
        entry,
        wrote_template: false,
        wrote_file: false,
    })
}

fn section_name_for_repo(repo: &str, override_name: Option<&str>) -> String {
    override_name
        .map(str::to_string)
        .unwrap_or_else(|| repo.rsplit('/').next().unwrap_or(repo).to_string())
}

fn select_asset(assets: &[String], asset_filter: Option<&str>) -> Result<String> {
    let candidates = assets
        .iter()
        .filter(|asset| !is_auxiliary_asset(asset))
        .collect::<Vec<_>>();

    if let Some(filter) = asset_filter {
        let matches = candidates
            .into_iter()
            .filter(|asset| asset.contains(filter))
            .collect::<Vec<_>>();
        return match matches.as_slice() {
            [asset] => Ok((*asset).to_string()),
            [] => bail!(
                "no release asset matched --asset {filter:?}; available assets:\n{}",
                format_asset_list(assets)
            ),
            _ => bail!(
                "--asset {filter:?} matched multiple assets:\n{}\nUse a more specific --asset value.",
                matches.into_iter().map(|s| format!("  - {s}")).join("\n")
            ),
        };
    }

    let scored = candidates
        .into_iter()
        .map(|asset| (asset_score(asset), asset))
        .filter(|(score, _)| *score > 0)
        .sorted_by(|(left_score, left), (right_score, right)| {
            right_score.cmp(left_score).then_with(|| left.cmp(right))
        })
        .collect::<Vec<_>>();

    let Some((best_score, best_asset)) = scored.first() else {
        bail!(
            "could not infer a release asset for this platform; choose one with --asset. Available assets:\n{}",
            format_asset_list(assets)
        );
    };

    let tied = scored
        .iter()
        .filter(|(score, _)| score == best_score)
        .collect::<Vec<_>>();
    if tied.len() > 1 {
        bail!(
            "multiple release assets look equally good for this platform:\n{}\nChoose one with --asset.",
            tied.into_iter()
                .map(|(_, asset)| format!("  - {asset}"))
                .join("\n")
        );
    }

    Ok((*best_asset).to_string())
}

fn asset_score(asset: &str) -> i32 {
    let lower = asset.to_lowercase();
    if is_auxiliary_asset(&lower) {
        return -100;
    }

    let mut score = 0;
    let arch_aliases = match std::env::consts::ARCH {
        "x86_64" => vec!["x86_64", "amd64", "x64"],
        "aarch64" => vec!["aarch64", "arm64"],
        "arm" => vec!["armv7", "arm-", "arm_"],
        "x86" => vec!["i686", "i386", "x86"],
        other => vec![other],
    };
    if arch_aliases.iter().any(|alias| lower.contains(alias)) {
        score += 20;
    }

    match std::env::consts::OS {
        "linux" => {
            if lower.contains("linux") {
                score += 20;
            }
            if lower.contains("musl") {
                score += 6;
            } else if lower.contains("gnu") {
                score += 3;
            }
            if lower.contains("windows") || lower.contains("darwin") || lower.contains("apple") {
                score -= 30;
            }
        }
        "macos" => {
            if lower.contains("darwin") || lower.contains("apple") || lower.contains("macos") {
                score += 20;
            }
            if lower.contains("linux") || lower.contains("windows") {
                score -= 30;
            }
        }
        "windows" => {
            if lower.contains("windows") || lower.contains("pc-windows") || lower.ends_with(".exe")
            {
                score += 20;
            }
            if lower.contains("msvc") {
                score += 5;
            }
            if lower.contains("linux") || lower.contains("darwin") || lower.contains("apple") {
                score -= 30;
            }
        }
        os => {
            if lower.contains(os) {
                score += 20;
            }
        }
    }

    if [
        ".tar.gz",
        ".tar.xz",
        ".zip",
        ".gz",
        ".exe",
        ".com",
        ".appimage",
    ]
    .iter()
    .any(|suffix| lower.ends_with(suffix))
    {
        score += 2;
    }

    score
}

fn is_auxiliary_asset(asset: &str) -> bool {
    let lower = asset.to_lowercase();
    [
        "checksum",
        "checksums",
        "sha256",
        "sha512",
        ".sig",
        ".asc",
        ".pem",
        ".txt",
        ".json",
        ".spdx",
        "sbom",
    ]
    .iter()
    .any(|marker| lower.contains(marker))
}

fn anchor_text_for_asset(asset_name: &str, tag_name: &str) -> String {
    let Some(version) = simple_semver(tag_name) else {
        return escape_regex_literal(asset_name);
    };
    let Some(version_start) = asset_name.find(version) else {
        return escape_regex_literal(asset_name);
    };

    let include_v = version_start > 0
        && asset_name[..version_start]
            .chars()
            .next_back()
            .is_some_and(|ch| ch == 'v' || ch == 'V');
    let replacement_start = if include_v {
        version_start - 'v'.len_utf8()
    } else {
        version_start
    };

    format!(
        "{}{}{}",
        escape_regex_literal(&asset_name[..replacement_start]),
        if include_v {
            "v?(\\d+\\.\\d+\\.\\d+)"
        } else {
            "(\\d+\\.\\d+\\.\\d+)"
        },
        escape_regex_literal(&asset_name[version_start + version.len()..])
    )
}

fn simple_semver(tag_name: &str) -> Option<&str> {
    let bytes = tag_name.as_bytes();
    for start in 0..bytes.len() {
        if !bytes[start].is_ascii_digit() {
            continue;
        }
        let mut dot_count = 0;
        let mut end = start;
        while end < bytes.len() && (bytes[end].is_ascii_digit() || bytes[end] == b'.') {
            if bytes[end] == b'.' {
                dot_count += 1;
            }
            end += 1;
        }
        if dot_count == 2 && tag_name[start..end].split('.').all(|part| !part.is_empty()) {
            return Some(&tag_name[start..end]);
        }
    }
    None
}

fn escape_regex_literal(value: &str) -> String {
    value
        .chars()
        .flat_map(|ch| match ch {
            '.' | '+' | '*' | '?' | '^' | '$' | '(' | ')' | '[' | ']' | '{' | '}' | '|' | '\\' => {
                vec!['\\', ch]
            }
            _ => vec![ch],
        })
        .collect()
}

fn render_definition(
    section_name: &str,
    repo: &str,
    anchor_text: &str,
    extract: Option<&str>,
    version: &str,
) -> String {
    let extract_line = extract
        .map(|target| format!("target_filename_to_extract_from_archive = {target}\n"))
        .unwrap_or_default();
    format!(
        "[{section_name}]\ntemplate = github_api_latest\nproject = {repo}\nanchor_text = {anchor_text}\n{extract_line}version = {version}\n"
    )
}

fn append_definition(
    config_path: &Path,
    existing_config: &str,
    needs_template: bool,
    entry: &str,
) -> Result<()> {
    let mut file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(config_path)?;

    if !existing_config.is_empty() && !existing_config.ends_with('\n') {
        writeln!(file)?;
    }
    if !existing_config.trim().is_empty() {
        writeln!(file)?;
    }
    if needs_template {
        writeln!(file, "{GITHUB_API_TEMPLATE}")?;
    }
    writeln!(file, "{entry}")?;
    Ok(())
}

fn has_section(config: &str, section_name: &str) -> bool {
    let expected = format!("[{section_name}]");
    config.lines().any(|line| line.trim() == expected)
}

fn validate_repo(repo: &str) -> Result<()> {
    let parts = repo.split('/').collect::<Vec<_>>();
    if parts.len() == 2 && parts.iter().all(|part| !part.trim().is_empty()) {
        Ok(())
    } else {
        bail!("GitHub repository must be in OWNER/REPO form")
    }
}

fn format_asset_list(assets: &[String]) -> String {
    assets.iter().map(|asset| format!("  - {asset}")).join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn options(repo: &str) -> AddGithubOptions {
        AddGithubOptions {
            repo: repo.to_string(),
            section_name: None,
            asset_filter: None,
            extract: None,
            dry_run: true,
        }
    }

    #[test]
    fn renders_starship_style_definition_without_version_in_asset_name() -> Result<()> {
        let release = GithubRelease {
            tag_name: "v1.9.1".to_string(),
            assets: vec!["starship-x86_64-unknown-linux-musl.tar.gz".to_string()],
        };

        let definition =
            definition_from_release("starship/starship", &release, &options("starship/starship"))?;

        assert_eq!(definition.section_name, "starship");
        assert_eq!(
            definition.entry,
            "[starship]\ntemplate = github_api_latest\nproject = starship/starship\nanchor_text = starship-x86_64-unknown-linux-musl\\.tar\\.gz\nversion = v1.9.1\n"
        );
        Ok(())
    }

    #[test]
    fn renders_ripgrep_style_definition_with_extract_target() -> Result<()> {
        let release = GithubRelease {
            tag_name: "14.1.1".to_string(),
            assets: vec!["ripgrep-14.1.1-x86_64-unknown-linux-musl.tar.gz".to_string()],
        };
        let mut options = options("BurntSushi/ripgrep");
        options.extract = Some("rg".to_string());

        let definition = definition_from_release("BurntSushi/ripgrep", &release, &options)?;

        assert_eq!(
            definition.entry,
            "[ripgrep]\ntemplate = github_api_latest\nproject = BurntSushi/ripgrep\nanchor_text = ripgrep-(\\d+\\.\\d+\\.\\d+)-x86_64-unknown-linux-musl\\.tar\\.gz\ntarget_filename_to_extract_from_archive = rg\nversion = 14.1.1\n"
        );
        Ok(())
    }

    #[test]
    fn asset_filter_must_identify_one_asset() {
        let assets = vec![
            "tool-linux-amd64.tar.gz".to_string(),
            "tool-linux-arm64.tar.gz".to_string(),
        ];

        let err = select_asset(&assets, Some("linux"))
            .unwrap_err()
            .to_string();

        assert!(err.contains("matched multiple assets"));
    }

    #[test]
    fn detects_existing_sections() {
        let config = "[template:github_api_latest]\nmethod = api_json\n\n[ripgrep]\nversion = 1\n";

        assert!(has_section(config, "template:github_api_latest"));
        assert!(has_section(config, "ripgrep"));
        assert!(!has_section(config, "starship"));
    }
}
